#If true then data for Manhunt will be loaded
Manhunt: true

#If true then the data for Conjoin will get Load
Conjoin: true

#If true then the data for Multiverse will get Load
Multiverse: true


#Set if for the manhunt friendly fire ist active or inactive Default: false
ManhuntFriendlyFire: false

#if true only the person who has the inventory role can access the inventory
CojoinAccessInventory: true
