name: gruppe
version: '${project.version}'
main: de.gruppe.plugin.Main
commands:
  conjoin:
    description: Assigns a player to control attack.

  conjoin start:
    description: Startet die conjoin

  conjoin attack:
    description: set player to attack controller

  conjoin break:
    description: set player to break controller

  conjoin inventory:
    description: set player to inventory controller

  conjoin movement:
    description: set player to attack controller

  setName:
    description: changes the name from a player

  manhunt:
    description: manhunt commands

  manhunt setTarget:
    description: set target for compass

  manhunt getCompass:
    description: get compass

  manhunt menu:
    description: open the menu

  manhunt setRole:
    description: set role
  manhunt setRole none:
    description: set role
  manhunt setRole hunter:
    description: set role
  manhunt setRole speedrunner:
    description: set role


