name: gruppe
version: '1.0-SNAPSHOT'
main: de.gruppe.plugin.Main
commands:
  conjoin:
    description: Assigns a player to control attack.
    usage: /<command>

  conjoin start:
    description: Startet die conjoin
    usage: /<command>

  conjoin attack:
    description: set player to attack controler
    usage: /<command> <player>

  conjoin break:
    description: set player to break controler
    usage: /<command> <player>

  conjoin inventory:
    description: set player to inventory controler
    usage: /<command> <player>

  conjoin movement:
    description: set player to attack controler
    usage: /<command> <player>

  setName:
    description: changes the name from a player

  manhunt:
    description: manhunt commands

  manhunt setTarget:
    description: set target for compass

  manhunt getCompass:
    description: get compass

  manhunt menu:
    description: open the menu


