name: gruppe
version: '1.0-SNAPSHOT'
main: de.gruppe.plugin.Main
commands:
  cojoin:
    description: Assigns a player to control attack.

  cojoin start:
    description: Startet die conjoin

  cojoin attack:
    description: set player to attack controller

  cojoin break:
    description: set player to break controller

  cojoin inventory:
    description: set player to inventory controller

  cojoin movement:
    description: set player to attack controller

  cojoin getroles:
    description: set player to attack controller

  cojoin createController:
    description: set player to attack controller

  cojoin setRole:
    description: set player to attack controller

  setName:
    description: changes the name from a player

  manhunt:
    description: manhunt commands

  manhunt setTarget:
    description: set target for compass

  manhunt getCompass:
    description: get compass

  manhunt menu:
    description: open the menu

  manhunt setRole:
    description: set role
  manhunt setRole none:
    description: set role
  manhunt setRole hunter:
    description: set role
  manhunt setRole speedrunner:
    description: set role

  multiverse:
    description: multiple worlds


