name: gruppe
version: '1.0-SNAPSHOT'
main: de.gruppe.plugin.Main
commands:
  cojoin:
    description: Assigns a player to control attack.

  setName:
    description: changes the name from a player

  manhunt:
    description: manhunt commands

  manhunt setTarget:
    description: set target for compass

  manhunt getCompass:
    description: get compass

  manhunt menu:
    description: open the menu

  manhunt setRole:
    description: set role
  manhunt setRole none:
    description: set role
  manhunt setRole hunter:
    description: set role
  manhunt setRole speedrunner:
    description: set role

  multiverse:
    description: multiple worlds

  Vanish:

  HideFromPlayer:

  Collidable:

  ShowToPlayer:

  God:

  Fly:

  menu:

  invsee:

  enderchest:


